import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useTheme } from '../contexts/ThemeContext';
import { 
  FileCheck, 
  CreditCard, 
  BookOpen, 
  Car, 
  Vote, 
  Fingerprint, 
  ChevronDown, 
  ShieldCheck, 
  Link as LinkIcon, 
  UserPlus,
  ArrowRight,
  ShieldAlert,
  HelpCircle
} from 'lucide-react';

const CredentialServicesPage: React.FC = () => {
  const { isDarkMode } = useTheme();
  const navigate = useNavigate();

  const services = [
    { 
      title: "Aadhaar Linking", 
      icon: <Fingerprint className="text-orange-500" />, 
      desc: "Synchronize your biometrics-based national ID with your CredChain UVID.", 
      status: "Available" 
    },
    { 
      title: "PAN Linking", 
      icon: <CreditCard className="text-blue-500" />, 
      desc: "Connect your Permanent Account Number for unified tax and financial auditing.", 
      status: "Available" 
    },
    { 
      title: "Passport Linking", 
      icon: <BookOpen className="text-emerald-500" />, 
      desc: "Digitalize your travel document metadata for faster airport clearance.", 
      status: "Coming Soon" 
    },
    { 
      title: "Driving License", 
      icon: <Car className="text-purple-500" />, 
      desc: "Link your transport department credentials for mobile verification.", 
      status: "Available" 
    },
    { 
      title: "Voter ID (EPIC)", 
      icon: <Vote className="text-red-500" />, 
      desc: "Verify your eligibility and link your Voter ID for zero-fraud voting.", 
      status: "Available" 
    },
    { 
      title: "UVID Registration", 
      icon: <UserPlus className="text-amber-500" />, 
      desc: "Initial step for newborns or unlinked citizens to join CredChain India.", 
      status: "Available" 
    },
  ];

  const faqs = [
    { 
      q: "What is a UVID?", 
      a: "A UVID (Universal Virtual Identity) is a unique, privacy-preserving identifier generated by CredChain. It acts as a single source of truth that links all your fragmented government IDs without exposing your sensitive data." 
    },
    { 
      q: "Is my data safe on the blockchain?", 
      a: "No personal identifiable information (PII) like your name or photo is stored on the public blockchain. Only cryptographic hashes and metadata transitions are recorded, ensuring your data is both private and immutable." 
    },
    { 
      q: "Can I link multiple credentials?", 
      a: "Yes, the primary purpose of CredChain is to link all your IDs (PAN, Aadhaar, Passport, etc.) into one verifiable digital container." 
    },
    { 
      q: "What happens after I link a credential?", 
      a: "Once linked, your credential undergoes verification by an officer. After approval, a digital signature is etched on the blockchain, and you can generate a secure QR for instant verification anywhere." 
    }
  ];

  const cardStyle = isDarkMode 
    ? "bg-[#0f0f11] border-white/10 hover:border-orange-500/30 text-white" 
    : "bg-white border-slate-200 hover:border-orange-200 text-slate-900 shadow-sm";

  return (
    <div className={`min-h-screen pt-24 pb-16 px-6 ${isDarkMode ? 'text-slate-300' : 'text-slate-600'}`}>
      <div className="container mx-auto max-w-7xl animate-in fade-in slide-in-from-bottom-4 duration-700">
        
        {/* Header */}
        <section className="mb-16">
          <h1 className={`text-4xl md:text-5xl font-bold mb-4 ${isDarkMode ? 'text-white' : 'text-slate-900'}`}>
            Credential Services
          </h1>
          <p className="text-xl text-slate-500 max-w-2xl">
            Unified access to all national identity and document services, secured by blockchain.
          </p>
        </section>

        {/* Services Grid */}
        <section className="mb-32">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {services.map((service, i) => (
              <div key={i} className={`p-8 rounded-2xl border flex flex-col transition-all group ${cardStyle}`}>
                <div className="flex justify-between items-start mb-6">
                  <div className={`p-3 rounded-xl bg-slate-500/10 group-hover:scale-110 transition-transform`}>
                    {service.icon}
                  </div>
                  <span className={`text-[10px] font-bold uppercase tracking-widest px-2.5 py-1 rounded-full border ${
                    service.status === 'Available' 
                      ? 'border-emerald-500/30 text-emerald-500 bg-emerald-500/10' 
                      : 'border-slate-500/30 text-slate-500'
                  }`}>
                    {service.status}
                  </span>
                </div>
                <h3 className="text-xl font-bold mb-3">{service.title}</h3>
                <p className={`text-sm mb-8 flex-grow ${isDarkMode ? 'text-slate-400' : 'text-slate-500'}`}>
                  {service.desc}
                </p>
                <button 
                  disabled={service.status !== 'Available'}
                  onClick={() => navigate('/citizen-portal')}
                  className={`w-full py-3 rounded-xl flex items-center justify-center gap-2 font-semibold transition-all ${
                  service.status === 'Available'
                    ? isDarkMode ? 'bg-white/5 hover:bg-orange-600 hover:text-white border border-white/10' : 'bg-slate-900 text-white hover:bg-orange-600'
                    : 'bg-slate-500/10 text-slate-500 cursor-not-allowed border border-transparent'
                }`}>
                  {service.status === 'Available' ? 'Start Linking' : 'Coming Soon'} 
                  {service.status === 'Available' && <ArrowRight size={16} />}
                </button>
              </div>
            ))}
          </div>
        </section>

        {/* How to Link */}
        <section className="mb-32">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-16 items-center">
            <div>
              <h2 className={`text-3xl font-bold mb-8 ${isDarkMode ? 'text-white' : 'text-slate-900'}`}>Linking your credentials</h2>
              <div className="space-y-10">
                {[
                  { icon: <UserPlus />, title: "1. Login / Register", desc: "Access the Citizen Portal using your Aadhaar-linked mobile number or biometric Auth." },
                  { icon: <FileCheck />, title: "2. Access Profile", desc: "Navigate to your dashboard and select 'Add New Credential'." },
                  { icon: <LinkIcon />, title: "3. Verify & Link", desc: "Enter details, upload document hash, and submit for officer verification." },
                ].map((step, i) => (
                  <div key={i} className="flex gap-6">
                    <div className={`flex-shrink-0 w-12 h-12 rounded-2xl flex items-center justify-center ${isDarkMode ? 'bg-orange-500/10 text-orange-400' : 'bg-orange-50 text-orange-600'}`}>
                      {step.icon}
                    </div>
                    <div>
                      <h4 className={`text-lg font-bold mb-1 ${isDarkMode ? 'text-white' : 'text-slate-800'}`}>{step.title}</h4>
                      <p className="text-slate-500">{step.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div className={`relative aspect-square md:aspect-video rounded-3xl border overflow-hidden flex items-center justify-center ${isDarkMode ? 'bg-blue-900/10 border-blue-500/20 shadow-[0_0_50px_rgba(59,130,246,0.1)]' : 'bg-blue-50 border-blue-100 shadow-xl'}`}>
                <ShieldCheck size={120} className="text-blue-500/40 animate-pulse" />
                <div className="absolute inset-x-0 bottom-0 p-8 backdrop-blur-md bg-white/5 border-t border-white/5">
                  <p className="text-xs font-medium text-center italic">
                    "All documents are processed using Zero-Knowledge Proof (ZKP) principles. 
                    Your privacy is guaranteed by mathematics, not just policy."
                  </p>
                </div>
            </div>
          </div>
        </section>

        {/* Security Section */}
        <section className={`mb-32 p-12 rounded-3xl border text-center ${isDarkMode ? 'bg-slate-900/50 border-white/5' : 'bg-slate-50 border-slate-200'}`}>
          <div className="max-w-2xl mx-auto">
            <ShieldAlert size={48} className="mx-auto text-blue-500 mb-6" />
            <h2 className={`text-3xl font-bold mb-6 ${isDarkMode ? 'text-white' : 'text-slate-900'}`}>Enterprise-Grade Security</h2>
            <p className="text-lg mb-8">
              CredChain uses a hybrid storage model. Sensitive personal data is <strong>hashed off-chain</strong>, while only 
              the <strong>cryptographic metadata</strong> is stored on the immutable blockchain.
            </p>
            <div className="flex justify-center gap-4 flex-wrap">
              <span className="px-4 py-2 rounded-full border border-blue-500/30 text-blue-500 text-xs font-bold uppercase tracking-widest">AES-256 Encryption</span>
              <span className="px-4 py-2 rounded-full border border-orange-500/30 text-orange-500 text-xs font-bold uppercase tracking-widest">Solidity Contracts</span>
              <span className="px-4 py-2 rounded-full border border-emerald-500/30 text-emerald-500 text-xs font-bold uppercase tracking-widest">Officer Verification</span>
            </div>
          </div>
        </section>

        {/* FAQ Accordion */}
        <section className="mb-32">
          <div className="text-center mb-16">
            <h2 className={`text-3xl font-bold mb-4 ${isDarkMode ? 'text-white' : 'text-slate-900'}`}>Common Questions</h2>
            <div className="flex justify-center"><HelpCircle className="text-slate-500" /></div>
          </div>
          <div className="max-w-3xl mx-auto space-y-4">
            {faqs.map((faq, i) => (
              <div key={i} className={`p-6 rounded-2xl border transition-all ${isDarkMode ? 'bg-[#0f0f11] border-white/5 hover:border-white/10' : 'bg-white border-slate-200 hover:shadow-md'}`}>
                <div className="flex justify-between items-center cursor-pointer group">
                  <h4 className={`font-bold pr-8 ${isDarkMode ? 'text-white group-hover:text-blue-400' : 'text-slate-800'}`}>{faq.q}</h4>
                  <ChevronDown size={20} className="text-slate-500 flex-shrink-0" />
                </div>
                <div className="mt-4 pt-4 border-t border-dashed border-slate-700/20 text-slate-500 leading-relaxed text-sm">
                  {faq.a}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Bottom CTA */}
        <section className="flex flex-col md:flex-row justify-center items-center gap-6 py-12 border-t border-white/5">
          <button 
            onClick={() => navigate('/citizen-portal')}
            className="w-full md:w-auto px-10 py-4 rounded-2xl bg-orange-600 text-white font-bold hover:bg-orange-700 transition-all flex items-center justify-center gap-3 shadow-lg shadow-orange-600/20"
          >
            Citizen Portal <ArrowRight size={20} />
          </button>
          <button 
            onClick={() => navigate('/administrative')}
            className={`w-full md:w-auto px-10 py-4 rounded-2xl font-bold transition-all flex items-center justify-center gap-3 border ${
              isDarkMode ? 'bg-white/5 border-white/10 hover:bg-white/10 text-white' : 'bg-white border-slate-200 hover:bg-slate-50'
            }`}
          >
            Officer Portal <ShieldCheck size={20} />
          </button>
        </section>

      </div>
    </div>
  );
};

export default CredentialServicesPage;
